---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: nginx
  name: nginx
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 8000
          name: port-8000
          protocol: TCP
          
---
## From the trait gateway 
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: nginx
  name: nginx
  namespace: demo
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: nginx

